name: frontend
description: Cliente Flutter do Duolinfo.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.2
  google_sign_in: ^6.2.2
  google_sign_in_web: ^0.12.4
  flutter_dotenv: ^6.0.1
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
